# this is a workflow must has secrets.DOCKERHUB_TOKEN
# most use as github.event.pull_request.merged == true
name: docker-image-latest

on:
  workflow_call: # https://docs.github.com/actions/using-workflows/reusing-workflows#using-inputs-and-secrets-in-a-reusable-workflow
    inputs:
      docker_hub_user:
        description: 'name of docker hub user'
        default: ''
        required: true
        type: string
      docker_image_name:
        description: 'name of docker image'
        default: ''
        required: true
        type: string
      push_remote_flag:
        description: 'flag for push to remote'
        default: false
        required: false
        type: boolean
      build_branch_name:
        description: 'name of branch for build default is main'
        default: 'main'
        required: false
        type: string

env:
  DOCKER_IMAGE_PLATFORMS: linux/amd64,linux/arm64/v8 # change to your platforms for release
#  DOCKER_IMAGE_PLATFORMS: linux/amd64,linux/386,linux/arm64/v8,linux/arm/v7

jobs:
  info_print:
    runs-on: ubuntu-latest
    steps:
      - name: print inputs args
        run: |
          echo " CI ${CI}"
          echo " GITHUB_ACTION ${GITHUB_ACTION}"
          echo " RUNNER_DEBUG ${RUNNER_DEBUG}"
          echo " RUNNER_OS ${RUNNER_OS}"
          echo " runner.os ${{ runner.os }}"
          echo " RUNNER_ARCH ${RUNNER_ARCH}"
          echo ""
          echo ""
          echo " GITHUB_JOB ${GITHUB_JOB}"
          echo " GITHUB_EVENT_NAME ${GITHUB_EVENT_NAME}"
          echo " github.event_name ${{ github.event_name }}"
          echo " github.event.pusher.name ${{ github.event.pusher.name }}"
          echo " github.event.pusher.email ${{ github.event.pusher.email }}"
          echo " github.event.sender.name ${{ github.event.sender.name }}"
          echo " github.event.sender.email ${{ github.event.sender.email }}"
          echo ""
          echo " GITHUB_SHA ${GITHUB_SHA}"
          echo " GITHUB_REF_TYPE ${GITHUB_REF_TYPE}"
          echo " GITHUB_REF ${GITHUB_REF}"
          echo " github.ref ${{ github.ref }}"
          echo " GITHUB_REF_NAME ${GITHUB_REF_NAME}"
          echo " GITHUB_BASE_REF ${GITHUB_BASE_REF}"
          echo " github.base_ref ${{ github.base_ref }}"
          echo " GITHUB_HEAD_REF ${GITHUB_HEAD_REF}"
          echo " github.head_ref ${{ github.head_ref }}"
          echo ""
          echo " github.event.pull_request.title ${{ github.event.pull_request.title }}"
          echo " github.event.pull_request.state ${{ github.event.pull_request.state }}"
          echo " github.event.pull_request.merged ${{ github.event.pull_request.merged }}"
          echo " github.event.pull_request.base.sha main ${{ github.event.pull_request.base.sha || 'main' }}"
          echo " github.event.pull_request.head.sha github.ref ${{ github.event.pull_request.head.sha || github.ref }}"
          echo ""
          echo "docker_hub_user= ${{ inputs.docker_hub_user }}"
          echo "docker_image_name= ${{ inputs.docker_image_name }}"
          echo "push_remote_flag= ${{ inputs.push_remote_flag }}"
          echo "github.event.inputs.push_remote_flag= ${{ github.event.inputs.push_remote_flag }}"

  docker-image-buildx:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        docker_image: # change this for build dry-run
          - platform: linux/amd64
          # - platform: linux/386
          # - platform: linux/arm64/v8
          # - platform: linux/arm/v7
    runs-on: ${{ matrix.os }}
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.docker_image_name }}
          tags: |
            # set latest tag for main branch https://github.com/docker/metadata-action#latest-tag
            type=raw,value=latest,enable=true
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build dry
        uses: docker/build-push-action@v5 # https://github.com/docker/build-push-action
        with:
          context: .
          file: Dockerfile
          platforms: ${{ matrix.docker_image.platform }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
          no-cache: false
          pull: true
          push: false

  docker-image-push:
    runs-on: ubuntu-latest
    needs:
      - docker-image-buildx
    if: ${{ inputs.push_remote_flag }} == true
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ inputs.docker_image_name }}
          tags: |
            # type semver https://github.com/docker/metadata-action#typesemver
            type=raw,value=latest,enable=true
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: "Login into registry as user: inputs.docker_hub_user"
        uses: docker/login-action@v3
        with:
          username: ${{ inputs.docker_hub_user }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        id: docker_push
        uses: docker/build-push-action@v5 # https://github.com/docker/build-push-action
        with:
          context: .
          file: Dockerfile
          platforms: ${{ env.DOCKER_IMAGE_PLATFORMS }}
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ steps.meta.outputs.tags }}
          no-cache: false
          pull: true
          push: true
